apiVersion: v1
kind: Pod
metadata:
    name: hadoop-slave1
    labels:
      app: hadoop-slave1
spec:
  containers:
    - name: hadoop-slave1
      image: myregistry.local:5000/hadoop_uninstall:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: [ "infinity" ] 
      resources:
         requests:
           cpu: "3000m"
      #    memory: "600Mi"
      ports:
        - containerPort: 22
        - containerPort: 50070  
        - containerPort: 50010
        - containerPort: 50075
        - containerPort: 50475
        - containerPort: 50020  
        - containerPort: 9000  
        - containerPort: 8040
        - containerPort: 8041   
        - containerPort: 8042 
      #env:
      #  - name: HADOOP_NODE_TYPE
      #    value: datanode
      #  - name: HDFS_MASTER_SERVICE
      #    valueFrom:
      #      configMapKeyRef:
      #        name: ku8-hadoop-conf
      #        key: HDFS_MASTER_SERVICE
      #  - name: HDOOP_YARN_MASTER
      #    valueFrom:
      #      configMapKeyRef:
      #        name: ku8-hadoop-conf
      #        key: HDOOP_YARN_MASTER    
  #nodeSelector:
  #  diskspeed: k8s-master    
  restartPolicy: Always
