apiVersion: v1
kind: Service
metadata:
  name: k8s-hadoop-master
spec:
  type: NodePort
  selector:
    app: k8s-hadoop-master
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 50070
      targetPort: 50070
      nodePort: 32007


