apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master
  labels:
    app: hadoop-master
spec:
  containers:
    - name: hadoop-master
      image: myregistry.local:5000/hadoop_uninstall:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: [ "infinity" ] 
      ports:
        - containerPort: 22
        - containerPort: 3333
        - containerPort: 8000
        - containerPort: 8020
        - containerPort: 8088
        - containerPort: 9000
        - containerPort: 50070  
      resources:
         requests:
           cpu: "1000m"
      #    memory: "600Mi"
      volumeMounts:
        #- name: hadoop-conf
        #  mountPath: /opt/hadoop/etc/hadoop
  volumes:
    - name: hadoop-conf
      hostPath:
        path: /tmp/hadoop-conf
        type: Directory
  restartPolicy: Always
