apiVersion: v1
kind: Pod
metadata:
  name: yarn-node
  labels:
    app: yarn-node
spec:
  containers:
    - name: yarn-node
      image: myregistry.local:5000/hadoop_uninstall
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: [ "infinity" ] 
      ports:
        - containerPort: 3333
        - containerPort: 8000
        - containerPort: 8088
        - containerPort: 9000
        - containerPort: 50070  
        - containerPort: 8040
        - containerPort: 8041   
        - containerPort: 8042     
      resources:
         requests:
           cpu: "1000m"
      #    memory: "600Mi"   
      #env:
      #  - name: HADOOP_NODE_TYPE
      #    value: yarnnode
      #  - name: HDFS_MASTER_SERVICE
      #    valueFrom:
      #      configMapKeyRef:
      #        name: ku8-hadoop-conf
      #        key: HDFS_MASTER_SERVICE
      #  - name: HDOOP_YARN_MASTER
      #    valueFrom:
      #      configMapKeyRef:
      #        name: ku8-hadoop-conf
      #        key: HDOOP_YARN_MASTER          
  restartPolicy: Always
